### ISSUE TITLE
Can you write what it does in the About section

### ISSUE THREAD

**Issue by xen-42** [QuentinGruber/ghostMatterNerf#1]
Just like a "Makes it so Ghost Matter cannot hurt you" or something. This will show up on the mod website and in the mod manager. Cheers.

**Comment by Tllya** [comment]
++

**Comment by xen-42** [comment]
![image](https://user-images.githubusercontent.com/22628069/164523335-d5b99c01-9519-499a-874f-4b6d188b123d.png)

You might also want to add some spaces to the name! Will make it look better on the website

**Comment by QuentinGruber** [comment]
Hey @xen-42 thanks for these suggestions 😄 , now that I have made them, what do I need to do to get this updated? Do I need to release a new version?

**Comment by xen-42** [comment]
No problem! For the About section it gets automatically updated don't worry about that. For the prettier name in the manifest yeah you just have to make a new release. Be sure to increment the version number in the release tag and also in your manifest.json file.

**Comment by QuentinGruber** [comment]
That's a pretty cool system you have for mods, congrats on that. Hopefully what I did is correct.

**Comment by xen-42** [comment]
Raicuparta gets all the credit for that, I just help out a bit with maintaining the infrastructure. And yep it all looks good!
